language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install nose"
  - "pip install pylint"
  - "pip install pycodestyle"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs Pygments"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=plyara --cover-xml
  - pylint plyara.py
  - pylint --disable=C0103,C0111 setup.py
  - pycodestyle plyara.py
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
