language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - "pip install nose"
  - "pip install pycodestyle"
  - "pip install pydocstyle"
  - "pip install pyflakes"
  - "pip install coverage"
  - "pip install codacy-coverage"
  - "pip install collective.checkdocs Pygments"
  - "python setup.py install"
script:
  - nosetests --with-coverage --cover-package=plyara --cover-xml
  - pycodestyle --max-line-length=120 plyara/core.py
  - pycodestyle --max-line-length=120 plyara/exceptions.py
  - pycodestyle --max-line-length=120 plyara/command_line.py
  - pycodestyle --max-line-length=120 setup.py
  - pydocstyle --ignore=D203,D205,D208,D209,D213,D300,D400,D401,D403 plyara/core.py
  - pydocstyle --ignore=D203,D205,D208,D209,D213,D300,D400,D401,D403 plyara/exceptions.py
  - pydocstyle --ignore=D203,D205,D208,D209,D213,D300,D400,D401,D403 plyara/command_line.py
  - pydocstyle --ignore=D100 setup.py
  - pyflakes plyara/core.py
  - pyflakes plyara/exceptions.py
  - pyflakes plyara/command_line.py
  - pyflakes setup.py
  - python setup.py checkdocs
after_success:
  - python-codacy-coverage
